# Generated by Django 4.2.2 on 2023-06-15 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_rename_authors_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[('DEFAULT', 'default'), ('IN_USE', 'In_use'), ('DONE', 'Done')], default=('DEFAULT', 'default'))),
                ('start', models.DateField(db_index=True)),
                ('end', models.DateField(db_index=True)),
                ('book_in_order', models.ManyToManyField(to='core.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
