# Generated by Django 4.2.2 on 2023-06-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DEFAULT', 'default'), ('IN_USE', 'In_use'), ('DONE', 'Done')], default=('DEFAULT', 'default'), max_length=10),
        ),
    ]
