# Generated by Django 4.2.2 on 2023-06-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='to_change',
            field=models.BooleanField(default=False),
        ),
    ]
