# Generated by Django 4.2.2 on 2023-06-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_to_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mod_after_created',
            field=models.BooleanField(default=False),
        ),
    ]
